/* Accounting Workbench UI. Shares the core authenticated API and responsive components. */
let axData=null,axTab='health',axForm=null,axSubmission=null;
const axDefs={
 contact:['People','Add contact','Register a member, customer, supplier, borrower, tenant or staff member.','name|Full name','roles|Roles (comma-separated)|text|CUSTOMER','phone|Phone','reference|Member / source reference'],
 invoice:['Documents','Create invoice / bill','Creates a receivable or payable and its linked accounting entry.','kind|Document type|select|AR,AP','contact_id|Customer / supplier|contacts','date|Transaction date|date','due_date|Due date|date','amount|Total amount|number','account_code|Revenue / expense account|accounts','reference|Invoice / bill number','description|Particulars'],
 payment:['Documents','Allocate payment','Select an outstanding invoice. For rental balances, this also updates the tenant balance.','document_id|Outstanding document|documents','date|Payment date|date','amount|Amount paid|number','fund_account_code|Cash / bank account|funds','reference|Receipt / payment reference'],
 asset:['Assets','Register asset','Opening assets carry existing cost and depreciation without recording a new cash payment.','name|Asset name','date|Acquisition / opening date|date','amount|Original cost|number','residual|Residual value|number|0','life_months|Useful life in months|number|60','location|Location','custodian|Custodian','opening|Historical opening asset|checkbox','opening_depreciation|Opening accumulated depreciation|number|0','fund_account_code|Acquisition payment account|funds','reference|Asset / source reference'],
 depreciation:['Assets','Post depreciation','Uses the registered useful life when amount is blank. One posting per asset per month.','asset_id|Asset|assets','date|Posting date|date','amount|Amount (blank = scheduled amount)|number','reference|Depreciation reference'],
 product:['Inventory','Add agricultural product','P06 stock tracking. Rice and palay remain in P02.','name|Product name','business|Business / crop','unit|Stock unit|text|kg','reference|Reference'],
 stock:['Inventory','Record stock movement','Receive purchases or opening stock, sell products, or record an approved loss.','product_id|Product|products','mode|Movement|select|RECEIVE,OPENING,SALE,LOSS','date|Transaction date|date','quantity|Quantity|number','amount|Purchase cost / sale proceeds|number','batch|Batch / harvest reference','contact_id|Customer / supplier|contacts','payment_type|Settlement|select|CASH,CREDIT','fund_account_code|Cash / bank account|funds','reference|Source document'],
 'stock-count':['Inventory','Record stock count','Shortages use current cost. For a surplus, enter the reviewed value of the additional stock.','product_id|Product|products','date|Count date|date','counted|Physical quantity counted|number','amount|Value of surplus (if any)|number','reference|Signed count-sheet reference'],
 'migration-batch':['History','Start historical batch','Use one batch per project/book. Source dates must be on or before the cutover date.','name|Batch / manual book name','cutover|Last historical date|date','reference|Reference'],
 'migration-row':['History','Import historical rows','Download the CSV template. Save incomplete records as drafts; Preview validates accounting before posting.','batch_id|Draft batch|batches','rows|Historical CSV|migrationcsv'],
 'migration-preview':['History','Preview historical batch','Validates every row inside a rolled-back transaction. No journal records are retained.','batch_id|Draft batch|batches'],
 'migration-post':['History','Post historical batch','Posts the complete reviewed batch atomically. Repeating the submission does not post it twice.','batch_id|Draft batch|batches','confirmation|Type POST HISTORICAL BATCH'],
 'opening-loan':['History','Bring forward loan balance','Enter outstanding principal at cutover, not original principal plus past repayments. Future interest starts at the opening date.','contact_id|Borrower|contacts','date|Opening date|date','due_date|Due date|date','amount|Outstanding principal|number','interest_rate|Annual interest rate|number|0','reference|Manual loan ledger reference'],
 'opening-rental':['History','Bring forward tenant balance','Enter the verified unpaid tenant balance at cutover.','unit_id|Rental unit|units','date|Opening date|date','due_date|Due date|date','amount|Outstanding rent / utility balance|number','reference|Manual tenant ledger reference'],
 share:['Members','Record member share movement','Members need the MEMBER role in People. Opening balances use the opening equity clearing account.','contact_id|Member|contacts','mode|Movement|select|CONTRIBUTION,WITHDRAW','date|Transaction date|date','amount|Amount|number','opening|Historical opening balance|checkbox','fund_account_code|Cash / bank account|funds','reference|Share receipt / approval'],
 distribution:['Members','Post annual surplus allocation','Uses approved percentage settings. Requires a positive annual surplus and reconciled supporting ledgers.','year|Financial year|number','date|Approved allocation date|date','reference|Board / approval reference'],
 'bank-account':['Cash & Bank','Add bank account','Create a separate ledger account for an actual bank account.','code|Unused account code (10xx)','name|Bank and account name','reference|Reference'],
 statement:['Cash & Bank','Import bank statement','Positive amounts are bank credits to your funds; negative amounts are withdrawals. Opening plus movements must equal closing.','account_code|Bank / cash account|funds','date_from|Statement start|date','date_to|Statement end|date','opening|Opening balance|number','closing|Closing balance|number','reference|Statement reference','rows|Statement CSV|statementcsv'],
 'statement-match':['Cash & Bank','Match statement row','Open a statement below to see unmatched bank rows and eligible ledger line numbers.','row_id|Bank statement row number|number','line_id|Matching ledger line number|number','reference|Review reference'],
 'statement-finalize':['Cash & Bank','Finalize bank reconciliation','Requires all statement rows matched and the adjusted difference to equal zero.','statement_id|Statement|statements','reference|Reviewer reference'],
 'cash-count':['Cash & Bank','Record cash count','Records the physical count and difference without inventing an accounting adjustment.','date|Count date|date','fund_account_code|Cash account|funds','amount|Physical cash counted|number','reference|Signed count sheet'],
 job:['Services & Leases','Create service job','Draft jobs do not affect accounts until completed and billed.','contact_id|Customer|contacts','subproject_id|Service|services','date|Job date|date','quantity|Quantity|number','rate|Agreed unit rate|number','operator|Operator','equipment|Equipment','reference|Job order number'],
 'job-complete':['Services & Leases','Complete and bill job','Recognizes the agreed revenue and actual direct cost; credit jobs create an invoice.','job_id|Draft job|jobs','date|Completion date|date','direct_cost|Actual direct cost paid|number|0','payment_type|Settlement|select|CASH,CREDIT','fund_account_code|Cash / bank account|funds','reference|Completion / billing reference'],
 lease:['Services & Leases','Record lease period','Effective-dated tenant and rent terms used by billing for matching dates. Overlapping leases are rejected.','unit_id|Rental unit|units','tenant|Tenant name','date_from|Lease start|date','date_to|Lease end|date','rent|Monthly rent|number','reference|Lease agreement number'],
 journal:['Review','Post reviewed journal','For general adjustments. Use dedicated modules for controlled balances such as loans, stock, assets and receivables.','date|Posting date|date','lines|Journal lines|journal','reference|Adjustment reference','description|Particulars'],
 recurring:['Review','Save recurring journal','Creates a reusable template; each month still requires review and posting.','name|Template name','lines|Journal lines|journal','reference|Template reference','description|Particulars'],
 'recurring-post':['Review','Post recurring journal','A template can post only once per month.','template_id|Template|recurring','date|Posting date|date','reference|Voucher reference'],
 'close-review':['Review','Review month','Saves the reviewed reports and discrepancies as a permanent snapshot. Period locking remains in Accounting Periods.','month|Month (YYYY-MM)','status|Review status|select|REVIEW,VERIFIED','reference|Review notes / sign-off'],
 interproject:['Review','Record interproject transaction','Posts linked entries to both projects in one transaction.','target_project_id|Other project|projects','mode|Transaction|select|ADVANCE,SERVICE_CREDIT','date|Transaction date|date','amount|Amount|number','fund_account_code|Sending cash / bank|funds','target_fund|Receiving cash / bank|funds','reference|Transfer / service reference'],
 attachment:['Evidence','Attach source document','PDF, PNG, JPG or WebP up to 5 MB. Documents are protected by project access and included in backups.','entry_id|Journal entry number|number','file|Source document|file']
};
const axAdminOps=new Set(['asset','depreciation','stock-count','migration-batch','migration-row','migration-preview','migration-post','opening-loan','opening-rental','share','distribution','bank-account','statement','statement-match','statement-finalize','cash-count','journal','recurring','recurring-post','close-review','interproject']);
function axAllowed(op){if(axAdminOps.has(op)&&!roleIs('SUPERADMIN'))return false;const type=currentProjectObj()?.type;if(['product','stock','stock-count'].includes(op))return type==='COMMUNAL';if(['job','job-complete'].includes(op))return type==='FARM_SERVICE';if(['lease','opening-rental'].includes(op))return type==='RENTAL';if(['opening-loan','loan-terms','loan-writeoff'].includes(op))return type==='LOAN';if(['p02-count','p02-cost'].includes(op))return type==='PALAY';return true;}
function axTable(rows,cols,action){if(!rows?.length)return '<div class="empty">No records yet.</div>';return `<div class="table-wrap"><table class="table"><thead><tr>${cols.map(c=>`<th>${esc(c[1])}</th>`).join('')}${action?'<th>Open</th>':''}</tr></thead><tbody>${rows.map(r=>`<tr>${cols.map(([key])=>`<td>${esc(typeof r[key]==='object'?JSON.stringify(r[key]):r[key]??'')}</td>`).join('')}${action?`<td><button class="btn soft" onclick="${action}(${Number(r.id)})">Open</button></td>`:''}</tr>`).join('')}</tbody></table></div>`;}
async function pageWorkbench(){if(state.currentProject==='consolidated'){$('content').innerHTML=head('Accounting Workbench','Select a project in the top bar to work with its supporting records.');return;}axData=await api(`/api/workbench/overview?projectId=${currentPid()}&to=${state.year}-12-31`);axRender();}
function axRender(){const groups=['Health','Loans','People','Documents','Assets','Inventory','History','Members','Cash & Bank','Services & Leases','Review','Evidence'];if(!groups.includes(axTab))axTab='Health';const buttons=Object.entries(axDefs).filter(([op,d])=>d[0]===axTab&&axAllowed(op)).map(([op,d])=>`<button class="btn primary" onclick="axOpen('${op}')">${esc(d[1])}</button>`).join(' ');let body='';
 if(axTab==='Health')body=`<div class="notice ${axData.health.ok?'info':'bad'}"><strong>${axData.health.ok?'Supporting balances agree':'Review needed'}</strong> • As of ${esc(axData.health.as_of)}. Bank reconciliation and source-document completeness require separate review.</div>${axTable(axData.health.controls,[['name','Control'],['difference','Difference (PHP)'],['ok','Agrees']])}${axData.health.issues.map(x=>`<p class="notice bad">${esc(x)}</p>`).join('')}`;
 if(axTab==='Loans')body=(axData.loan_schedules||[]).map(l=>`<h3>${esc(l.borrower)} • ${esc(l.method)} • ${esc(l.annual_rate)}%</h3>${axTable(l.rows,[['date','Due date'],['principal','Scheduled principal']])}`).join('')||'<div class="empty">No loans yet.</div>';
 if(axTab==='People')body=axTable(axData.contacts,[['id','ID'],['name','Name'],['roles','Roles'],['reference','Reference']]);
 if(axTab==='Documents')body=axTable(axData.documents,[['id','ID'],['kind','Type'],['contact_name','Contact'],['reference','Document'],['date','Date'],['due_date','Due'],['total','Total'],['paid','Allocated'],['outstanding','Outstanding'],['days_overdue','Days overdue']]);
 if(axTab==='Documents')body+=axTable(axData.advances,[['id','Advance'],['name','Contact'],['kind','Type'],['remaining','Remaining']]);
 if(axTab==='Assets')body=axTable(axData.assets,[['id','ID'],['name','Asset'],['acquired','Acquired'],['cost','Cost'],['accumulated','Depreciation'],['book_value','Book value'],['life_months','Life (months)']]);
 if(axTab==='Inventory')body=currentProjectObj().type==='PALAY'?'<div class="notice info">P02 stock, batch processing and consignment remain in Project Operations.</div>':axTable(axData.products,[['id','ID'],['name','Product'],['business','Business'],['unit','Unit'],['quantity','Quantity'],['value','Value'],['unit_cost','Unit cost']]);
 if(axTab==='History')body='<div class="notice info">Keep verified opening balances separate from transactions already included in those balances. Preview each batch before posting. Missing supporting records appear in Health.</div>'+axTable(axData.batches,[['id','ID'],['name','Batch'],['cutover','Cutover'],['status','Status']],'axBatch');
 if(axTab==='Members')body=axTable(axData.shares.map(x=>({...x,balance:x.balance_cents/100})),[['id','ID'],['name','Member'],['balance','Share balance']])+axTable(axData.distributions,[['id','ID'],['year','Allocation year'],['reference','Approval']]);
 if(axTab==='Members')body+=axTable(axData.member_payables,[['id','Payable'],['name','Member'],['amount','Amount'],['paid','Paid']]);
 if(axTab==='Cash & Bank')body=axTable(axData.statements,[['id','ID'],['account_code','Account'],['date_from','From'],['date_to','To'],['status','Status']],'axStatement');
 if(axTab==='Services & Leases')body=axTable(axData.jobs,[['id','Job'],['customer','Customer'],['date','Date'],['quantity','Quantity'],['status','Status']])+axTable(axData.leases,[['id','Lease'],['unit_id','Unit'],['tenant','Tenant'],['date_from','From'],['date_to','To']]);
 if(axTab==='Review')body=axTable(axData.reviews,[['id','Review'],['month','Month'],['status','Status'],['reason','Sign-off'],['created_at','Saved']])+axTable(axData.recurring,[['id','Template'],['name','Recurring journal']]);
 if(axTab==='Evidence')body=axTable(axData.attachments,[['id','ID'],['entry_id','Journal entry'],['name','File'],['created_at','Attached']],'axAttachment');
 $('content').innerHTML=head('Accounting Workbench',`${currentProjectObj().code} • Supporting records, historical migration and reconciliation`)+`<div class="panel"><div class="toolbar" style="flex-wrap:wrap">${groups.map(g=>`<button class="btn ${axTab===g?'primary':'soft'}" onclick="axTab='${g}';axRender()">${esc(g)}</button>`).join('')}</div><div class="toolbar" style="flex-wrap:wrap;margin:16px 0"><input class="input" placeholder="Search this view…" aria-label="Search this view" oninput="document.querySelectorAll('#content tbody tr').forEach(r=>r.hidden=!r.textContent.toLowerCase().includes(this.value.toLowerCase()))">${buttons}<button class="btn soft" onclick="axExport()">Export this view</button><button class="btn soft" onclick="pageWorkbench()">Refresh</button></div>${body}</div>`;
}
function axOptions(type){let rows=type==='projects'?state.projects.filter(p=>p.id!==currentPid()).map(p=>[p.id,p.code+' • '+p.name]):(axData[type]||[]).map(x=>{if(type==='accounts'||type==='funds')return [x.code,x.code+' • '+x.name];if(type==='documents')return [x.id,`${x.kind} ${x.reference} • ${x.contact_name} • ${money(x.outstanding)}`];if(type==='units')return [x.id,x.unit_code+' • '+(x.tenant||'Vacant')];return [x.id,x.name||x.loan_no||x.customer||x.reference||`${type} #${x.id}`];});return '<option value="">Select…</option>'+rows.map(([v,label])=>`<option value="${esc(v)}">${esc(label)}</option>`).join('');}
function axField(spec){const [key,label,type='text',def='']=spec.split('|'),id='ax_'+key;
 if(type==='journal')return `<div class="field span2"><label for="${id}">${esc(label)}</label><div id="axLines"></div><button class="btn soft" type="button" onclick="axAddLine()">+ Journal line</button><small>Each line must have one debit or one credit.</small></div>`;
 if(['migrationcsv','statementcsv','membercsv'].includes(type))return `<div class="field span2"><label for="${id}">${esc(label)}</label><button type="button" class="btn soft" onclick="axTemplate('${type}')">Download CSV template</button><input class="input" id="${id}" type="file" accept=".csv,text/csv"><small>CSV exported from Excel is supported. Preview rows before posting.</small><div id="axCsvPreview"></div></div>`;
 if(type==='file')return `<div class="field span2"><label for="${id}">${esc(label)}</label><input class="input" id="${id}" type="file" accept="application/pdf,image/png,image/jpeg,image/webp"></div>`;
 if(type==='select')return `<div class="field"><label for="${id}">${esc(label)}</label><select class="select" id="${id}">${def.split(',').map(v=>`<option>${esc(v)}</option>`).join('')}</select></div>`;
 if(!['text','date','number','checkbox'].includes(type))return `<div class="field"><label for="${id}">${esc(label)}</label><select class="select" id="${id}">${axOptions(type)}</select></div>`;
 if(type==='checkbox')return `<div class="field"><label><input id="${id}" type="checkbox"> ${esc(label)}</label></div>`;
 return `<div class="field"><label for="${id}">${esc(label)}</label><input class="input" id="${id}" type="${type}" ${type==='number'?'step="any"':''} value="${esc(type==='date'?today():key==='year'?state.year:def)}"></div>`;
}
function axOpen(op){axForm=op;axSubmission=crypto.randomUUID();const d=axDefs[op];modal(d[1],`<div class="notice info">${esc(d[2])}</div><form id="axForm"><div class="form-grid">${d.slice(3).map(axField).join('')}</div></form><div id="axResult"></div>`,`<button class="btn soft" onclick="closeModal()">Cancel</button><button class="btn primary" id="axSaveBtn" onclick="axSave()">${op==='migration-preview'?'Preview':'Review and save'}</button>`,true);if($('axLines')){axAddLine();axAddLine();}const file=$('ax_rows');if(file)file.onchange=async()=>{try{const rows=axCsv(await file.files[0].text());$('axCsvPreview').innerHTML=axTable(rows.slice(0,5),Object.keys(rows[0]||{}).map(k=>[k,k]))+`<p>${rows.length} rows read.</p>`;}catch(e){toast(e.message,'error')}};}
function axAddLine(){const div=document.createElement('div');div.className='form-grid ax-line';div.style.marginBottom='8px';div.innerHTML=`<select class="select" data-key="account_code">${axOptions('accounts')}</select><input class="input" data-key="debit" type="number" min="0" step="0.01" placeholder="Debit"><input class="input" data-key="credit" type="number" min="0" step="0.01" placeholder="Credit"><button class="btn soft" type="button" onclick="this.parentElement.remove()">Remove</button>`;$('axLines').appendChild(div);}
function axCsv(text){text=text.replace(/^\uFEFF/,'');const matrix=[];let row=[],cell='',quoted=false;for(let i=0;i<text.length;i++){const ch=text[i];if(ch==='"'){if(quoted&&text[i+1]==='"'){cell+='"';i++;}else quoted=!quoted;}else if(ch===','&&!quoted){row.push(cell);cell='';}else if(ch==='\n'&&!quoted){row.push(cell.replace(/\r$/,''));if(row.some(x=>x.trim()))matrix.push(row);row=[];cell='';}else cell+=ch;}if(quoted)throw Error('Unclosed CSV quote');if(cell||row.length){row.push(cell.replace(/\r$/,''));matrix.push(row);}const keys=matrix.shift()?.map(s=>s.trim())||[];if(!keys.length||new Set(keys).size!==keys.length)throw Error('CSV needs unique column headings');return matrix.filter(r=>r.some(x=>x.trim())).map((r,i)=>{if(r.length!==keys.length)throw Error(`CSV row ${i+2} has the wrong number of columns`);return Object.fromEntries(keys.map((k,j)=>[k,r[j]]));});}
function axDownload(name,text,type='text/csv'){const url=URL.createObjectURL(new Blob([text],{type})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function axTemplate(type){const s=type==='membercsv'?'contact_id,amount\n1,100\n':type==='statementcsv'?'date,reference,amount\n2026-01-01,DEPOSIT-001,1000\n':'row_key,operation,date,reference,description,debit_account,credit_account,amount,contact_id,due_date,interest_rate\nBOOK1-001,journal,2025-12-31,OPEN-001,Verified opening cash,1000,3000,1000,,,\n';axDownload(type==='membercsv'?'member-allocation-template.csv':type==='statementcsv'?'bank-statement-template.csv':'historical-records-template.csv',s);}
async function axSave(){const btn=$('axSaveBtn');if(btn.disabled)return;btn.disabled=true;try{const b={projectId:currentPid()};for(const spec of axDefs[axForm].slice(3)){const [key,label,type='text']=spec.split('|');if(type==='journal'){b.lines=[...document.querySelectorAll('.ax-line')].map(row=>Object.fromEntries([...row.querySelectorAll('[data-key]')].map(e=>[e.dataset.key,e.dataset.key==='account_code'?e.value:Number(e.value||0)])));continue;}const el=$('ax_'+key);if(type==='file'){const f=el.files[0];if(!f)throw Error('Choose a file');if(f.size>5*1024*1024)throw Error('Maximum file size is 5 MB');b.name=f.name;b.mime=f.type;b.base64=await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result.split(',')[1]);r.onerror=reject;r.readAsDataURL(f)});continue;}if(['migrationcsv','statementcsv','membercsv'].includes(type)){if(!el.files[0])throw Error('Choose a CSV file');b.rows=axCsv(await el.files[0].text());if(type==='migrationcsv')b.rows=b.rows.map(r=>{if(r.operation==='journal')r.lines=[{account_code:r.debit_account,debit:Number(r.amount)},{account_code:r.credit_account,credit:Number(r.amount)}];return r;});continue;}b[key]=type==='checkbox'?el.checked:type==='number'?(el.value===''?undefined:Number(el.value)):el.value;}
 const fingerprint=JSON.stringify(b);if(axSave.lastFingerprint&&axSave.lastFingerprint!==fingerprint)axSubmission=crypto.randomUUID();axSave.lastFingerprint=fingerprint;const r=await api('/api/workbench/'+axForm,{method:'POST',headers:{'Idempotency-Key':axSubmission},body:JSON.stringify(b)});if(axForm==='member-preview'){$('axResult').innerHTML=`<div class="notice info">${esc(r.basis)}</div>${axTable(r.rows,[['name','Member'],['interest_on_share_capital','Share interest'],['patronage_refund','Patronage'],['amount','Total']])}`;btn.disabled=false;}else if(axForm==='migration-preview'){$('axResult').innerHTML=`<div class="notice info">Preview succeeded. ${r.rows.length} rows validated. No entries were saved.</div>${axTable(r.health.controls,[['name','Control'],['difference','Difference']])}`;btn.disabled=false;}else{closeModal();toast(r.message||'Saved successfully.','success');await pageWorkbench();}
 }catch(e){$('axResult').innerHTML=`<div class="notice bad">${esc(e.message)}</div>`;btn.disabled=false;}}
async function axStatement(id){try{const r=await api(`/api/workbench/statement?projectId=${currentPid()}&id=${id}`);modal('Bank reconciliation',`<div class="notice info">Ledger ${money(r.ledger_cents/100)} • Statement ${money(r.closing_cents/100)} • Uncleared ${money(r.uncleared_cents/100)} • Difference ${money(r.difference_cents/100)}</div><h3>Bank rows</h3>${axTable(r.rows.map(x=>({...x,amount:x.amount_cents/100})),[['id','Bank row'],['date','Date'],['reference','Reference'],['amount','Amount'],['journal_line_id','Matched ledger line']])}<h3>Uncleared ledger movements</h3>${axTable(r.unmatched.map(x=>({...x,amount:x.amount_cents/100})),[['id','Ledger line'],['tx_date','Date'],['ref','Reference'],['amount','Amount']])}`,`<button class="btn primary" onclick="closeModal()">Close</button>`,true);}catch(e){toast(e.message,'error')}}
async function axBatch(id){try{const r=await api(`/api/workbench/batch?projectId=${currentPid()}&id=${id}`);modal('Historical batch',axTable(r.rows.map(x=>({...JSON.parse(x.payload),entry_id:x.entry_id})),[['row_key','Source row'],['operation','Operation'],['date','Date'],['reference','Reference'],['amount','Amount'],['entry_id','Posted entry']]),`<button class="btn primary" onclick="closeModal()">Close</button>`,true);}catch(e){toast(e.message,'error')}}
async function axAttachment(id){const a=axData.attachments.find(x=>x.id===id);try{const blob=await api(`/api/workbench/attachment?projectId=${currentPid()}&id=${id}`);const url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=a.name;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(e){toast(e.message,'error')}}
function axExport(){const key={'Loans':'loans','Health':'health','People':'contacts','Documents':'documents','Assets':'assets','Inventory':'products','History':'batches','Members':'shares','Cash & Bank':'statements','Services & Leases':'jobs','Review':'reviews','Evidence':'attachments'}[axTab];let rows=key==='health'?axData.health.controls:axData[key];if(!rows?.length)return toast('No rows to export.');const keys=Object.keys(rows[0]).filter(k=>!['payload','snapshot'].includes(k));const cell=v=>'"'+String(v??'').replace(/^[=+@-]/,"'$&").replaceAll('"','""')+'"';axDownload(`CoopLedger-${currentProjectObj().code}-${axTab.replaceAll(' ','-')}.csv`,[keys.join(','),...rows.map(r=>keys.map(k=>cell(typeof r[k]==='object'?JSON.stringify(r[k]):r[k])).join(','))].join('\r\n'));}
Object.assign(axDefs,{
 advance:['Documents','Record advance / deposit','Keep advance cash separate from income and expenses until applied or liquidated.','contact_id|Contact|contacts','kind|Type|select|CUSTOMER_DEPOSIT,SUPPLIER_PREPAYMENT,STAFF_ADVANCE','date|Date|date','amount|Amount|number','fund_account_code|Cash / bank|funds','reference|Receipt / advance reference'],
 'advance-settle':['Documents','Apply / refund advance','Apply to an invoice, refund unused funds, or liquidate a staff/supplier advance to an approved expense.','advance_id|Advance|advances','mode|Action|select|APPLY,REFUND,LIQUIDATE','document_id|Invoice (for APPLY)|documents','account_code|Expense account (for LIQUIDATE)|accounts','date|Settlement date|date','amount|Amount|number','fund_account_code|Cash / bank (refund)|funds','reference|Settlement reference'],
 'credit-note':['Documents','Issue credit note','Reduces an outstanding invoice with a reviewed revenue or expense adjustment. Inventory returns must also be accounted for separately.','document_id|Outstanding document|documents','account_code|Original revenue / expense account|accounts','date|Date|date','amount|Credit amount|number','reference|Approved credit-note reference'],
 'asset-dispose':['Assets','Dispose / sell asset','Removes asset cost and accumulated depreciation and records gain or loss.','asset_id|Asset|assets','date|Disposal date|date','amount|Sale proceeds (zero if none)|number|0','fund_account_code|Receive proceeds into|funds','reference|Disposal approval'],
 'p02-count':['Inventory','P02 physical stock count','Enter total batch stock including stock held on consignment. Warehouse-only counts must first include confirmed consigned stock.','item_id|Stock item|palay_items','batch_id|Batch|palay_batches','date|Count date|date','counted|Actual total quantity (kg)|number','amount|Reviewed surplus value, if any|number','reference|Count and approval reference'],
 'p02-cost':['Inventory','P02 processing cost','Adds reviewed processing cost to existing batch stock. Later cost effects must be reviewed in Health.','item_id|Stock item|palay_items','batch_id|Batch|palay_batches','contact_id|Supplier (credit)|contacts','date|Cost date|date','amount|Processing cost|number','payment_type|Payment|select|CASH,CREDIT','fund_account_code|Cash / bank|funds','reference|Processing cost reference'],
 'loan-terms':['Loans','Set / restructure loan terms','Versioned terms preserve previous payments. Changes cannot overlap already posted payments. Principal schedules are equal installments; interest follows the selected day-count rule.','loan_id|Loan|loans','date|Effective date|date','annual_rate|Annual interest rate (%)|number','method|Interest basis|select|ACTUAL_365,ACTUAL_360,ZERO_INTEREST','installments|Monthly principal installments|number|1','first_due|First due date|date','reference|Loan agreement / restructuring approval'],
 'loan-writeoff':['Loans','Write off loan principal','Posts an approved principal loss while preserving the original loan and audit history.','loan_id|Loan|loans','date|Approval date|date','amount|Principal written off|number','reference|Write-off approval'],
 'member-schedule':['Members','Approve member payout schedule','CSV columns: contact_id,amount. Total must equal the approved member distribution payable.','distribution_id|Annual allocation|distributions','rows|Approved member schedule CSV|membercsv','reference|Schedule approval'],
 'member-pay':['Members','Pay member distribution','Pays an approved member amount once and retains the payable history.','payable_id|Unpaid member amount|member_payables','date|Payment date|date','fund_account_code|Pay from|funds','reference|Payout receipt'],
 'interproject-settle':['Review','Settle interproject balance','Uses the original interproject entry to identify the debtor and creditor. Both project entries post together.','entry_id|Original interproject journal entry number|number','date|Settlement date|date','amount|Amount|number','fund_account_code|Debtor payment fund|funds','target_fund|Creditor receipt fund|funds','reference|Settlement reference'],
 'statement-reopen':['Cash & Bank','Reopen reconciliation','Records the reason and previous reconciliation before allowing corrections.','statement_id|Statement|statements','reference|Reason for reopening']
});
['credit-note','asset-dispose','p02-count','p02-cost','loan-terms','loan-writeoff','member-schedule','member-pay','interproject-settle','statement-reopen'].forEach(x=>axAdminOps.add(x));

axDefs['member-preview']=['Members','Preview member allocation','Suggests member amounts from recorded time-weighted shares and member revenue patronage. Review before approval.','distribution_id|Annual allocation|distributions'];axAdminOps.add('member-preview');
